ignore:
  - "src/quansino/type_hints.py"
  - "src/quansino/protocols.py"
comment: false
coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto
